import "../globals.css";
import { Provider } from "@/components/ui/provider";
import { Locale } from "@/i18n/get-dictionary";
import type { Metadata } from "next";
import { Geist, Geist_Mono, Poppins } from "next/font/google";
import ChakraRootProvider from "@/components/ui/ChakraRootProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["400", "700"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Portfolio - João Rocha",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: { lang: Locale };
}>) {
  const { lang } = await params;

  return (
    <html
      lang={lang}
      className="dark"
      style={{ colorScheme: "dark" }} // ✅ garante estilo fixo no SSR
      suppressHydrationWarning        // ✅ evita warnings residuais
    >
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${poppins.variable}`}
      >
        <ChakraRootProvider>
          <Provider>{children}</Provider>
        </ChakraRootProvider>
      </body>
    </html>
  );
}
